### ISSUE TITLE
Primary Exchange Error - Unsupported Keyword

### ISSUE THREAD

**Issue by Sinansi** [lbilli/Jib.jl#11]
The following is Apple Inc description from Interactive Brokers Trader Workstation TWS

_APPLE INC
--
Underlying: AAPL
Security Type: STK  
Currency: USD
Exchange: SMART
Primary Exchange: NASDAQ
Symbol: AAPL
Sector: Technology
Industry: Computers
Category: Computers
Issuer Country: US 
Stock type: COMMON_

This is the jib contract I am trying to create
_JC = Jib.Contract(symbol = "AAPL", secType = "STK", currency = "USD", exchange = "SMART", primaryExchange="NASDAQ");_

I get the following error
**_got unsupported keyword argument "primaryExchange"_**

But when I check the documentation (?Jib.Contract) it says the "primaryExchange" is a valid keyword.

Could you please emphasize how to state the primary exchange?

Thank you!

**Comment by lbilli** [comment]
In general, I haven't coded many keyword argument constructors, just default ones.

In the case of `Contract` only a [subset of the fields](https://github.com/lbilli/Jib.jl/blob/e2c8853f04c970c922daad4594bec53a7c521209/src/types_mutable.jl#L21) have been exposed as keyword arguments.

So, the most generic way to fill a `Contract` is something like:
```julia
c = Jib.Contract()

c.symbol = "AAPL"
c.currency = "USD"
c.primaryExchange = ...
... # Any other field you need
```
The same applies to `Order`, `ScannerSubscription`, `ComboLeg` and `ExecutionFilter`.

`Contract()` allows **some** keyword arguments and therefore these shortcuts are also possible:
```julia
c = Jib.Contract(conId=265598, currency="USD") # AAPL
# or
c = Jib.Contract(symbol="AAPL", secType="STK", exchange="SMART", currency="USD") 

# which you can always follow with:
c.primaryExchange = ...
c.localSymbol = ...
```
On a side note, `primaryExchange` is rarely needed to find a `Contract` and that's why it's been left as a keyword argument.
However, nothing prevents you from writing your own `Contract` constructor along [these](https://github.com/lbilli/Jib.jl/blob/e2c8853f04c970c922daad4594bec53a7c521209/src/types_mutable.jl#L21) lines.

**Comment by Sinansi** [comment]
Thanks alot! The dot operator solved it. Initializing the primary exchange using "c.primaryExchange" works.
True, the primary exchange is typically not mentioned. But I am planning to trade stocks based in non-US markets.
I wish to avoid symbols clash for similar symbols if any.
